/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package firstgradleproject;

public class App {
    public String getGreeting() {
        return "Hello World! From my first Gradle Project";
    }
/*Hello this is my comment just for commit */
    public static void main(String[] args) 
    {
        System.out.println(new App().getGreeting());
        System.out.println("New Line - Hello");
        /*this is my comment */
        //Next comment
        int a=10,b=11;
        if (a!=b) 
        System.out.println("This message after if is scuccessful");
        else  System.out.println("This message after if is un-scuccessful");
        
    }
}
